/**
 * AUTO-GENERATED by scripts/fetch-commute-times.ts
 * To regenerate: npm run fetch-commutes:tfl
 * Values are one-way minutes from TfL Journey Planner (shortest itinerary).
 */

export interface CommuteTimes {
  [homeLocation: string]: {
    [workLocation: string]: number;
  };
}

export const commuteTimes: CommuteTimes = {
  "Brixton": {
    "City of London": 17,
    "Canary Wharf": 0,
    "King's Cross": 16,
    "Shoreditch": 0,
    "Westminster": 15,
    "South Bank": 10,
    "Paddington": 27,
    "Victoria": 7,
    "Liverpool Street": 24,
    "Oxford Circus": 11,
    "Green Park": 9
  },
  "Fulham": {
    "City of London": 29,
    "Canary Wharf": 0,
    "King's Cross": 26,
    "Shoreditch": 0,
    "Westminster": 15,
    "South Bank": 20,
    "Paddington": 17,
    "Victoria": 12,
    "Liverpool Street": 37,
    "Oxford Circus": 21,
    "Green Park": 19
  },
  "Tooting": {
    "City of London": 22,
    "Canary Wharf": 0,
    "King's Cross": 28,
    "Shoreditch": 0,
    "Westminster": 27,
    "South Bank": 17,
    "Paddington": 32,
    "Victoria": 17,
    "Liverpool Street": 29,
    "Oxford Circus": 23,
    "Green Park": 21
  },
  "Sutton": {
    "City of London": 49,
    "Canary Wharf": 0,
    "King's Cross": 49,
    "Shoreditch": 0,
    "Westminster": 46,
    "South Bank": 42,
    "Paddington": 52,
    "Victoria": 33,
    "Liverpool Street": 47,
    "Oxford Circus": 53,
    "Green Park": 49
  },
  "New Malden": {
    "City of London": 36,
    "Canary Wharf": 0,
    "King's Cross": 42,
    "Shoreditch": 0,
    "Westminster": 35,
    "South Bank": 24,
    "Paddington": 44,
    "Victoria": 33,
    "Liverpool Street": 44,
    "Oxford Circus": 37,
    "Green Park": 35
  },
  "Wimbledon": {
    "City of London": 30,
    "Canary Wharf": 0,
    "King's Cross": 36,
    "Shoreditch": 0,
    "Westminster": 28,
    "South Bank": 19,
    "Paddington": 26,
    "Victoria": 28,
    "Liverpool Street": 42,
    "Oxford Circus": 32,
    "Green Park": 30
  },
  "Richmond": {
    "City of London": 34,
    "Canary Wharf": 0,
    "King's Cross": 38,
    "Shoreditch": 0,
    "Westminster": 31,
    "South Bank": 21,
    "Paddington": 32,
    "Victoria": 26,
    "Liverpool Street": 44,
    "Oxford Circus": 33,
    "Green Park": 31
  },
  "Ealing": {
    "City of London": 28,
    "Canary Wharf": 0,
    "King's Cross": 30,
    "Shoreditch": 0,
    "Westminster": 33,
    "South Bank": 25,
    "Paddington": 7,
    "Victoria": 30,
    "Liverpool Street": 21,
    "Oxford Circus": 22,
    "Green Park": 27
  },
  "Hounslow": {
    "City of London": 57,
    "Canary Wharf": 0,
    "King's Cross": 48,
    "Shoreditch": 0,
    "Westminster": 44,
    "South Bank": 49,
    "Paddington": 41,
    "Victoria": 41,
    "Liverpool Street": 56,
    "Oxford Circus": 47,
    "Green Park": 39
  },
  "Croydon": {
    "City of London": 0,
    "Canary Wharf": 0,
    "King's Cross": 0,
    "Shoreditch": 0,
    "Westminster": 0,
    "South Bank": 0,
    "Paddington": 0,
    "Victoria": 0,
    "Liverpool Street": 0,
    "Oxford Circus": 0,
    "Green Park": 0
  },
  "Wimbledon Park": {
    "City of London": 42,
    "Canary Wharf": 0,
    "King's Cross": 38,
    "Shoreditch": 0,
    "Westminster": 31,
    "South Bank": 32,
    "Paddington": 24,
    "Victoria": 28,
    "Liverpool Street": 45,
    "Oxford Circus": 34,
    "Green Park": 32
  },
  "High Barnet": {
    "City of London": 36,
    "Canary Wharf": 0,
    "King's Cross": 28,
    "Shoreditch": 0,
    "Westminster": 43,
    "South Bank": 39,
    "Paddington": 47,
    "Victoria": 35,
    "Liverpool Street": 39,
    "Oxford Circus": 31,
    "Green Park": 33
  },
  "Sutton Cheam": {
    "City of London": 53,
    "Canary Wharf": 0,
    "King's Cross": 54,
    "Shoreditch": 0,
    "Westminster": 49,
    "South Bank": 47,
    "Paddington": 59,
    "Victoria": 34,
    "Liverpool Street": 56,
    "Oxford Circus": 49,
    "Green Park": 47
  },
  "Acton Common": {
    "City of London": 40,
    "Canary Wharf": 0,
    "King's Cross": 32,
    "Shoreditch": 0,
    "Westminster": 27,
    "South Bank": 32,
    "Paddington": 26,
    "Victoria": 24,
    "Liverpool Street": 42,
    "Oxford Circus": 31,
    "Green Park": 22
  },
  "South Ealing": {
    "City of London": 39,
    "Canary Wharf": 0,
    "King's Cross": 35,
    "Shoreditch": 0,
    "Westminster": 28,
    "South Bank": 34,
    "Paddington": 21,
    "Victoria": 25,
    "Liverpool Street": 42,
    "Oxford Circus": 31,
    "Green Park": 29
  },
  "Southfields": {
    "City of London": 39,
    "Canary Wharf": 0,
    "King's Cross": 35,
    "Shoreditch": 0,
    "Westminster": 28,
    "South Bank": 34,
    "Paddington": 21,
    "Victoria": 25,
    "Liverpool Street": 42,
    "Oxford Circus": 31,
    "Green Park": 29
  }
};
