/**
 * AUTO-GENERATED by scripts/fetch-commute-times.ts
 * To regenerate: npm run fetch-commutes:tfl
 * Values are one-way minutes from TfL Journey Planner (shortest itinerary).
 */

export interface CommuteTimes {
  [homeLocation: string]: {
    [workLocation: string]: number;
  };
}

export const commuteTimes: CommuteTimes = {
  "Brixton": {
    "City of London": 16,
    "Canary Wharf": 27,
    "King's Cross": 16,
    "Shoreditch": 34,
    "Westminster": 13,
    "South Bank": 14,
    "Paddington": 21,
    "Victoria": 7,
    "Liverpool Street": 23,
    "Oxford Circus": 11,
    "Green Park": 9
  },
  "Fulham": {
    "City of London": 32,
    "Canary Wharf": 36,
    "King's Cross": 27,
    "Shoreditch": 39,
    "Westminster": 19,
    "South Bank": 25,
    "Paddington": 14,
    "Victoria": 16,
    "Liverpool Street": 35,
    "Oxford Circus": 23,
    "Green Park": 21
  },
  "Tooting": {
    "City of London": 22,
    "Canary Wharf": 32,
    "King's Cross": 27,
    "Shoreditch": 37,
    "Westminster": 23,
    "South Bank": 19,
    "Paddington": 31,
    "Victoria": 18,
    "Liverpool Street": 28,
    "Oxford Circus": 22,
    "Green Park": 20
  },
  "Sutton": {
    "City of London": 48,
    "Canary Wharf": 48,
    "King's Cross": 52,
    "Shoreditch": 59,
    "Westminster": 45,
    "South Bank": 42,
    "Paddington": 58,
    "Victoria": 33,
    "Liverpool Street": 54,
    "Oxford Circus": 47,
    "Green Park": 45
  },
  "New Malden": {
    "City of London": 44,
    "Canary Wharf": 41,
    "King's Cross": 42,
    "Shoreditch": 53,
    "Westminster": 33,
    "South Bank": 24,
    "Paddington": 41,
    "Victoria": 31,
    "Liverpool Street": 46,
    "Oxford Circus": 37,
    "Green Park": 35
  },
  "Wimbledon": {
    "City of London": 37,
    "Canary Wharf": 36,
    "King's Cross": 35,
    "Shoreditch": 46,
    "Westminster": 28,
    "South Bank": 18,
    "Paddington": 27,
    "Victoria": 24,
    "Liverpool Street": 39,
    "Oxford Circus": 30,
    "Green Park": 28
  },
  "Richmond": {
    "City of London": 39,
    "Canary Wharf": 37,
    "King's Cross": 37,
    "Shoreditch": 50,
    "Westminster": 30,
    "South Bank": 20,
    "Paddington": 43,
    "Victoria": 25,
    "Liverpool Street": 43,
    "Oxford Circus": 32,
    "Green Park": 30
  },
  "Ealing": {
    "City of London": 31,
    "Canary Wharf": 34,
    "King's Cross": 29,
    "Shoreditch": 32,
    "Westminster": 26,
    "South Bank": 26,
    "Paddington": 10,
    "Victoria": 33,
    "Liverpool Street": 23,
    "Oxford Circus": 23,
    "Green Park": 24
  },
  "Hounslow": {
    "City of London": 71,
    "Canary Wharf": 75,
    "King's Cross": 69,
    "Shoreditch": 74,
    "Westminster": 66,
    "South Bank": 65,
    "Paddington": 45,
    "Victoria": 71,
    "Liverpool Street": 63,
    "Oxford Circus": 63,
    "Green Park": 64
  },
  "Croydon": {
    "City of London": 32,
    "Canary Wharf": 30,
    "King's Cross": 36,
    "Shoreditch": 44,
    "Westminster": 29,
    "South Bank": 27,
    "Paddington": 41,
    "Victoria": 16,
    "Liverpool Street": 39,
    "Oxford Circus": 31,
    "Green Park": 29
  },
  "Wimbledon Park": {
    "City of London": 43,
    "Canary Wharf": 45,
    "King's Cross": 38,
    "Shoreditch": 52,
    "Westminster": 30,
    "South Bank": 28,
    "Paddington": 25,
    "Victoria": 27,
    "Liverpool Street": 47,
    "Oxford Circus": 34,
    "Green Park": 32
  },
  "High Barnet": {
    "City of London": 38,
    "Canary Wharf": 52,
    "King's Cross": 29,
    "Shoreditch": 48,
    "Westminster": 43,
    "South Bank": 37,
    "Paddington": 42,
    "Victoria": 38,
    "Liverpool Street": 41,
    "Oxford Circus": 34,
    "Green Park": 36
  },
  "Sutton Cheam": {
    "City of London": 51,
    "Canary Wharf": 52,
    "King's Cross": 0,
    "Shoreditch": 62,
    "Westminster": 48,
    "South Bank": 46,
    "Paddington": 61,
    "Victoria": 36,
    "Liverpool Street": 58,
    "Oxford Circus": 50,
    "Green Park": 48
  },
  "Acton Common": {
    "City of London": 42,
    "Canary Wharf": 46,
    "King's Cross": 34,
    "Shoreditch": 55,
    "Westminster": 30,
    "South Bank": 37,
    "Paddington": 24,
    "Victoria": 27,
    "Liverpool Street": 43,
    "Oxford Circus": 34,
    "Green Park": 34
  },
  "South Ealing": {
    "City of London": 0,
    "Canary Wharf": 0,
    "King's Cross": 0,
    "Shoreditch": 0,
    "Westminster": 0,
    "South Bank": 0,
    "Paddington": 0,
    "Victoria": 0,
    "Liverpool Street": 0,
    "Oxford Circus": 0,
    "Green Park": 0
  },
  "Southfields": {
    "City of London": 40,
    "Canary Wharf": 42,
    "King's Cross": 35,
    "Shoreditch": 49,
    "Westminster": 27,
    "South Bank": 31,
    "Paddington": 22,
    "Victoria": 24,
    "Liverpool Street": 43,
    "Oxford Circus": 31,
    "Green Park": 29
  }
};
