/**
 * AUTO-GENERATED by scripts/fetch-commute-times.ts
 * To regenerate: npm run fetch-commutes:tfl
 * Values are one-way minutes from TfL Journey Planner (shortest itinerary).
 */

export interface CommuteTimes {
  [homeLocation: string]: {
    [workLocation: string]: number;
  };
}

export const commuteTimes: CommuteTimes = {
  "Brixton": {
    "City of London": 15,
    "Canary Wharf": 0,
    "King's Cross": 16,
    "Shoreditch": 0,
    "Westminster": 15,
    "South Bank": 15,
    "Paddington": 21,
    "Victoria": 7,
    "Liverpool Street": 22,
    "Oxford Circus": 11,
    "Green Park": 9
  },
  "Fulham": {
    "City of London": 31,
    "Canary Wharf": 0,
    "King's Cross": 25,
    "Shoreditch": 0,
    "Westminster": 16,
    "South Bank": 22,
    "Paddington": 13,
    "Victoria": 13,
    "Liverpool Street": 34,
    "Oxford Circus": 20,
    "Green Park": 18
  },
  "Tooting": {
    "City of London": 22,
    "Canary Wharf": 0,
    "King's Cross": 27,
    "Shoreditch": 0,
    "Westminster": 26,
    "South Bank": 19,
    "Paddington": 32,
    "Victoria": 18,
    "Liverpool Street": 29,
    "Oxford Circus": 22,
    "Green Park": 20
  },
  "Sutton": {
    "City of London": 48,
    "Canary Wharf": 0,
    "King's Cross": 47,
    "Shoreditch": 0,
    "Westminster": 45,
    "South Bank": 42,
    "Paddington": 52,
    "Victoria": 31,
    "Liverpool Street": 49,
    "Oxford Circus": 46,
    "Green Park": 44
  },
  "New Malden": {
    "City of London": 43,
    "Canary Wharf": 0,
    "King's Cross": 42,
    "Shoreditch": 0,
    "Westminster": 33,
    "South Bank": 23,
    "Paddington": 41,
    "Victoria": 31,
    "Liverpool Street": 45,
    "Oxford Circus": 37,
    "Green Park": 35
  },
  "Wimbledon": {
    "City of London": 37,
    "Canary Wharf": 0,
    "King's Cross": 35,
    "Shoreditch": 0,
    "Westminster": 27,
    "South Bank": 17,
    "Paddington": 27,
    "Victoria": 22,
    "Liverpool Street": 41,
    "Oxford Circus": 30,
    "Green Park": 28
  },
  "Richmond": {
    "City of London": 39,
    "Canary Wharf": 0,
    "King's Cross": 41,
    "Shoreditch": 0,
    "Westminster": 28,
    "South Bank": 18,
    "Paddington": 36,
    "Victoria": 25,
    "Liverpool Street": 40,
    "Oxford Circus": 35,
    "Green Park": 30
  },
  "Ealing": {
    "City of London": 29,
    "Canary Wharf": 0,
    "King's Cross": 28,
    "Shoreditch": 0,
    "Westminster": 25,
    "South Bank": 24,
    "Paddington": 9,
    "Victoria": 31,
    "Liverpool Street": 22,
    "Oxford Circus": 22,
    "Green Park": 23
  },
  "Hounslow": {
    "City of London": 53,
    "Canary Wharf": 0,
    "King's Cross": 46,
    "Shoreditch": 0,
    "Westminster": 41,
    "South Bank": 46,
    "Paddington": 38,
    "Victoria": 38,
    "Liverpool Street": 53,
    "Oxford Circus": 44,
    "Green Park": 36
  },
  "Croydon": {
    "City of London": 0,
    "Canary Wharf": 0,
    "King's Cross": 0,
    "Shoreditch": 0,
    "Westminster": 0,
    "South Bank": 0,
    "Paddington": 0,
    "Victoria": 0,
    "Liverpool Street": 0,
    "Oxford Circus": 0,
    "Green Park": 0
  },
  "Wimbledon Park": {
    "City of London": 42,
    "Canary Wharf": 0,
    "King's Cross": 36,
    "Shoreditch": 0,
    "Westminster": 27,
    "South Bank": 26,
    "Paddington": 24,
    "Victoria": 24,
    "Liverpool Street": 45,
    "Oxford Circus": 31,
    "Green Park": 29
  },
  "High Barnet": {
    "City of London": 38,
    "Canary Wharf": 0,
    "King's Cross": 29,
    "Shoreditch": 0,
    "Westminster": 42,
    "South Bank": 37,
    "Paddington": 43,
    "Victoria": 37,
    "Liverpool Street": 40,
    "Oxford Circus": 33,
    "Green Park": 35
  },
  "Sutton Cheam": {
    "City of London": 52,
    "Canary Wharf": 0,
    "King's Cross": 53,
    "Shoreditch": 0,
    "Westminster": 48,
    "South Bank": 46,
    "Paddington": 59,
    "Victoria": 34,
    "Liverpool Street": 56,
    "Oxford Circus": 49,
    "Green Park": 47
  },
  "Acton Common": {
    "City of London": 39,
    "Canary Wharf": 0,
    "King's Cross": 31,
    "Shoreditch": 0,
    "Westminster": 24,
    "South Bank": 30,
    "Paddington": 23,
    "Victoria": 21,
    "Liverpool Street": 40,
    "Oxford Circus": 27,
    "Green Park": 21
  },
  "South Ealing": {
    "City of London": 40,
    "Canary Wharf": 0,
    "King's Cross": 34,
    "Shoreditch": 0,
    "Westminster": 25,
    "South Bank": 28,
    "Paddington": 22,
    "Victoria": 22,
    "Liverpool Street": 43,
    "Oxford Circus": 29,
    "Green Park": 27
  },
  "Southfields": {
    "City of London": 40,
    "Canary Wharf": 0,
    "King's Cross": 34,
    "Shoreditch": 0,
    "Westminster": 25,
    "South Bank": 28,
    "Paddington": 22,
    "Victoria": 22,
    "Liverpool Street": 43,
    "Oxford Circus": 29,
    "Green Park": 27
  }
};
