name: Auto-merge Codex PRs

on:
  workflow_run:
    workflows: ["PR Build & Preview"]
    types:
      - completed

jobs:
  automerge:
    if: |
      github.event.workflow_run.conclusion == 'success' &&
      github.actor == 'github-actions[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Enable Auto-merge
        uses: peter-evans/enable-pull-request-automerge@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash
