name: Auto-merge Codex PRs

on:
  workflow_run:
    workflows: ["PR Build & Preview"]
    types:
      - completed

jobs:
  automerge:
    runs-on: ubuntu-latest
    # only run if the build succeeded and the PR was opened by your bot
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.pull_requests[0].user.login == 'github-actions[bot]'
    steps:
      - name: Auto-merge the PR
        uses: peter-evans/enable-pull-request-automerge@v2
        with:
          # explicitly tell it which PR to merge
          pull-request-number: ${{ github.event.workflow_run.pull_requests[0].number }}
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash
